module:
  imports:
    - path: github.com/peaceiris/hugo-mod-bulma
    - path: github.com/peaceiris/hugo-mod-revealjs
    - path: github.com/peaceiris/hugo-mod-mermaidjs
    - path: github.com/peaceiris/hugo-mod-mathjax
    - path: github.com/jaywcjlove/hotkeys
      mounts:
        - source: dist
          target: assets/mod/hotkeys
