repo:
  URL: "https://github.com/peaceiris/hugo-theme-iris"
  branch: main
  contentDir: exampleSite/content

themeColor: "#ffffff" # smart phone's browser tab color

footer:
  copyright:
    name: peaceiris
    link: "https://peaceiris.com/"
    year: 2019

icon:
  favicon: /favicon/favicon64.ico
  x180: /favicon/apple-icon-180x180.jpg
  mstile: /favicon/ms-icon-150x150.jpg

enableBreadcrumbNavigation: true
enableRandomRecommendedPosts: true

shareButtons:
  twitter: true
  facebook: true
  pocket: true
  feedly: true
  hatenaBookmark: true
  reddit: true
