name: Dependabot Approve

on:
  pull_request_target:
    types:
      - opened

jobs:
  approve:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v1.3.1

      - uses: actions/checkout@v3

      - name: Approve
        if: |
          (steps.meta.outputs.package-ecosystem == 'github_actions') ||
          (steps.meta.outputs.package-ecosystem == 'npm_and_yarn' && steps.meta.outputs.directory == '/') ||
          (steps.meta.outputs.package-ecosystem == 'npm_and_yarn' && steps.meta.outputs.directory == '/exampleSite' && steps.meta.outputs.update-type == 'version-update:semver-minor') ||
          (steps.meta.outputs.package-ecosystem == 'npm_and_yarn' && steps.meta.outputs.directory == '/exampleSite' && steps.meta.outputs.update-type == 'version-update:semver-patch')
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr checkout "${PR_URL}" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ]; then
            gh pr review --approve "${PR_URL}"
          else
            echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
